export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    verifyMfa: "/auth/verify-mfa",
  },
  machines: "/machines",
  machineTarget: (id) => `/machines/${encodeURIComponent(id)}/target`,
  machineTestPlc: "/machines/test-plc",
  machineResetPlc: "/machines/reset-plc",
  machinePlcCommand: "/machines/plc-command",
  machineReadPlcValue: "/machines/read-plc-value",
  machineWritePlcValue: "/machines/write-plc-value",
  plcConfig: {
    ranges: "/plc-config/ranges",
    rangeRegisters: (rangeId) => `/plc-config/ranges/${encodeURIComponent(rangeId)}/registers`,
    export: "/plc-config/export",
  },
  scanners: "/scanners",
  scannerConnections: "/scanners/connections",
  scannerTestConnection: (id) => `/scanners/${encodeURIComponent(id)}/test-connection`,
  users: "/users",
  shifts: "/shifts",
  stationSettings: "/station-settings",
  roleAccessSettings: "/role-access-settings",
  traceability: {
    operations: "/traceability/operations",
    processFlow: "/traceability/process-flow",
    parts: "/traceability/parts",
    byPart: (partId) => `/traceability/${encodeURIComponent(partId)}`,
    journeyByPart: (partId) => `/traceability/journey/${encodeURIComponent(partId)}`,
    liveState: "/traceability/live-state",
    ioSnapshot: "/traceability/io-snapshot",
    machineStats: "/traceability/machine-stats",
    plcHealth: "/traceability/plc-health",
    scannerHealth: "/traceability/scanner-health",
    verify: "/traceability/verify",
    process: "/scan/process",
    plcStart: "/plc/operation/start",
    plcEnd: "/plc/operation/end",
    rework: "/traceability/rework",
    resetInterlock: "/traceability/reset-interlock",
    resetStation: "/traceability/reset-station",
    resetOperation: "/traceability/reset-operation",
    resetPlcOnly: "/traceability/reset-plc-only",
    deletePart: "/traceability/delete-part",
    bypass: "/traceability/bypass",
  },
  qrFormatRules: "/qr-format-rules",
  packing: {
    overview: "/packing/overview",
    startBox: "/packing/start-box",
    scan: "/packing/scan",
    boxByNumber: (boxNumber) => `/packing/box/${encodeURIComponent(boxNumber)}`,
    updateBox: (sessionId) => `/packing/box/${encodeURIComponent(sessionId)}`,
    deleteBox: (sessionId) => `/packing/box/${encodeURIComponent(sessionId)}`,
    managementSettings: "/packing/management/settings",
    managementSettingsLegacy: "/packing/settings",
    managementBoxes: "/packing/management/boxes",
    managementBoxesLegacy: "/packing/boxes",
    generateNext: "/packing/management/generate-next",
    generateNextLegacy: "/packing/generate-next",
  },
  dashboard: {
    summary: "/dashboard/summary",
    trends: "/dashboard/trends",
    report: "/dashboard/report",
    exportReport: "/dashboard/report/export-full",
    exportFullReport: "/dashboard/report/export-full",
    exportPartsReport: "/dashboard/report/export-parts",
    exportAuditReport: "/dashboard/report/export-audit",
  },
  reports: {
    data: "/reports/report/data",
    exportFull: "/reports/report/export-full",
    exportNG: "/reports/report/export-ng",
    exportParts: "/reports/report/export-parts",
    exportAudit: "/reports/report/export-audit",
  },
  alarms: {
    base: "/alarms",
    resolve: (id) => `/alarms/${encodeURIComponent(id)}/resolve`,
    resolveAll: "/alarms/resolve-all",
  },
  industrial: {
    health: "/industrial/health",
    metrics: "/industrial/metrics",
    watchdog: "/industrial/watchdog",
    sockets: "/industrial/sockets",
    queues: "/industrial/queues",
    timelineByOperation: (operationId) => `/industrial/timeline/${encodeURIComponent(operationId)}`,
    timelines: "/industrial/timelines",
  },
};
