export const APP_ROUTES = {
  login: "/login",
  root: "/",
  dashboard: "/dashboard",
  masterSettings: "/master-settings",
  production: "/production",
  traceability: "/traceability",
  machines: "/machines",
  plcConfig: "/plc-configuration",
  ioMonitor: "/io-monitor",
  users: "/users",
  scanners: "/scanners",
  shifts: "/shifts",
  qrRules: "/qr-format-rules",
  partJourney: "/component-journey",
  operatorView: "/operator-view",
  packing: "/packing",
};
