export const APP_ROUTES = {
  login: "/login",
  root: "/",
  dashboard: "/dashboard",
  masterSettings: "/master-settings",
  stationControls: "/station-controls",
  masterReports: "/master-reports",
  production: "/production",
  traceability: "/traceability",
  machines: "/machines",
  plcConfig: "/plc-configuration",
  ioMonitor: "/io-monitor",
  users: "/users",
  scanners: "/scanners",
  scannerMonitor: "/scanner-monitor",
  shifts: "/shifts",
  qrRules: "/qr-format-rules",
  partJourney: "/component-journey",
  processFlow: "/process-flow",
  operatorView: "/operator-view",
  packing: "/packing",
  packingManagement: "/packing-management",

  reports: "/reports",
};
